name = "task-manager"
main = "worker/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/public"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "task-manager-db"
database_id = "31aa2965-f554-4d66-bbb8-e3278e13208e"

[vars]
ENVIRONMENT = "production"
